FROM node:24-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm install 

RUN npm run db:generate

RUN cd packages/ui && npm run build:components && cd ../..

RUN cd apps/user-app && npm run build

CMD ["npm", "run", "start-user-app"]
